spring:
  application:
    name: auth-service
  cloud:
    config:
      name: auth
      profile: develop
  config:
    import: "optional:configserver:http://39.116.209.82:8888"

eureka:
  client:
    service-url:
      defaultZone: http://39.116.209.82:8761/eureka/
  instance:
    hostname: 39.116.209.82

encrypt:
  key : ${ENCRYPT_KEY}