spring:
  application:
    name: auth-service
  cloud:
    config:
      name: auth
      profile: deploy
  config:
    import: "optional:configserver:http://192.168.55.119:8888"
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone: http://192.168.55.119:8761/eureka/
  instance:
    hostname: 192.168.55.119
#
encrypt:
  key : ${ENCRYPT_KEY}

management:
  endpoints:
    web:
      exposure:
        include: refresh